project_id = "agctoypleepiuezdfytl"

[functions.create-pix-payment]
verify_jwt = true

[functions.create-payment-link]
verify_jwt = true

[functions.generate-insights]
verify_jwt = false

[functions.chatbot]
verify_jwt = true

[functions.analyze-financial-mood]
verify_jwt = true
